# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROTOC_GEN_GRPC_KOTLIN_VERSION: '1.0.0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Generate JVM
        env:
          PROTOC_GEN_GRPC_KOTLIN_JAR_URL: https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-kotlin/1.0.0/protoc-gen-grpc-kotlin-${{ env.PROTOC_GEN_GRPC_KOTLIN_VERSION }}-jdk7.jar
          PROTOC_GEN_GRPC_JAVA_URL: https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.34.0/protoc-gen-grpc-java-1.34.0-linux-x86_64.exe
          PROTOC_GEN_GRPC_JAVA_FILE_NAME: protoc-gen-grpc-java.exe
        run: |
          mkdir -p src/main/java
          mkdir -p src/main/grpckt
          mkdir -p src/main/grpc

          wget $PROTOC_GEN_GRPC_KOTLIN_JAR_URL
          wget $PROTOC_GEN_GRPC_JAVA_URL -O $PROTOC_GEN_GRPC_JAVA_FILE_NAME

          chmod a+x protoc-gen-grpc-kotlin.sh
          chmod a+x $PROTOC_GEN_GRPC_JAVA_FILE_NAME

          protoc --plugin=protoc-gen-grpc-java=${{ env.PROTOC_GEN_GRPC_JAVA_FILE_NAME }} --plugin=protoc-gen-grpckt=protoc-gen-grpc-kotlin.sh --grpc-java_out="./src/main/grpc" --grpckt_out="./src/main/grpckt" --java_out="./src/main/java" --proto_path="./" *.proto

      - name: Pushes to nextershop-pb-jvm
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'src'
          destination_repo: 'SCGWEDOtech/nexter-p2-nextershop-pb-jvm'
          user_email: 'kekhuay@users.noreply.github.com'
          user_name: 'kekhuay'
          commit_message: 'Update minor version from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}'
