name: Generate JavaScript

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate JavaScript
        run: |
          mkdir pb-js
          npx -p grpc-tools grpc_tools_node_protoc --proto_path=./ --js_out=import_style=commonjs,binary:./pb-js --grpc_out=grpc_js:./pb-js ./*.proto

      - name: Pushes generated files to JavaScript repository
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'pb-js/*'
          destination_repo: 'kekhuay/protobuf-js-example'
          user_email: 'kekhuay@users.noreply.github.com'
          user_name: 'kekhuay'
          commit_message: 'Update minor version from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}'
