# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Generate JVM
        env:
          PROTOC_GEN_GRPC_KOTLIN_VERSION: '1.0.0'
        run: |
          mkdir -p generated/java
          mkdir -p generated/grpckt
          curl "https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-kotlin/1.0.0/protoc-gen-grpc-kotlin-${PROTOC_GEN_GRPC_KOTLIN_VERSION}-jdk7.jar" --output "protoc-gen-grpc-kotlin-${PROTOC_GEN_GRPC_KOTLIN_VERSION}-jdk7.jar"
          chmod +x protoc-gen-grpc-kotlin.sh
          protoc --plugin=protoc-gen-grpckt=protoc-gen-grpc-kotlin.sh --grpckt_out="./generated/grpckt" --java_out="./generated/java"  --proto_path="./" *.proto
